services:
  python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-scanner-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    restart: unless-stopped
    mem_limit: 1g

  vite-react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-scanner-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    mem_limit: 1g

  mongo:
    image: mongo:8.0
    container_name: cloud-scanner-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:8-alpine
    container_name: cloud-scanner-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
