services:
  python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-scanner-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "5000:5000"
    restart: unless-stopped

  vite-react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-scanner-frontend
    ports:
      - "5173:80"
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    container_name: cloud-scanner-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
