/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScansScanIdRouteImport } from './routes/scans.$scanId'
import { Route as ScansFileScanIdRouteImport } from './routes/scans/file/$scanId'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansScanIdRoute = ScansScanIdRouteImport.update({
  id: '/scans/$scanId',
  path: '/scans/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansFileScanIdRoute = ScansFileScanIdRouteImport.update({
  id: '/scans/file/$scanId',
  path: '/scans/file/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/scan': typeof ScanRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/file/$scanId': typeof ScansFileScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/scan': typeof ScanRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/file/$scanId': typeof ScansFileScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/scan': typeof ScanRoute
  '/scans/$scanId': typeof ScansScanIdRoute
  '/scans/file/$scanId': typeof ScansFileScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/scan'
    | '/scans/$scanId'
    | '/scans/file/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/scan' | '/scans/$scanId' | '/scans/file/$scanId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/scan'
    | '/scans/$scanId'
    | '/scans/file/$scanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ScanRoute: typeof ScanRoute
  ScansScanIdRoute: typeof ScansScanIdRoute
  ScansFileScanIdRoute: typeof ScansFileScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$scanId': {
      id: '/scans/$scanId'
      path: '/scans/$scanId'
      fullPath: '/scans/$scanId'
      preLoaderRoute: typeof ScansScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/file/$scanId': {
      id: '/scans/file/$scanId'
      path: '/scans/file/$scanId'
      fullPath: '/scans/file/$scanId'
      preLoaderRoute: typeof ScansFileScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ScanRoute: ScanRoute,
  ScansScanIdRoute: ScansScanIdRoute,
  ScansFileScanIdRoute: ScansFileScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
