const Vulnerability = {
  // S3
  public_s3_bucket: "public_s3_bucket",
  s3_bucket_versioning_disabled: "s3_bucket_versioning_disabled",
  s3_bucket_logging_disabled: "s3_bucket_logging_disabled",
  s3_bucket_block_public_access_disabled:
    "s3_bucket_block_public_access_disabled",
  unencrypted_s3_bucket: "unencrypted_s3_bucket",
  s3_mfa_delete_disabled: "s3_mfa_delete_disabled",
  s3_no_lifecycle: "s3_no_lifecycle",
  s3_cors_all_origins: "s3_cors_all_origins",
  s3_bucket_no_tags: "s3_bucket_no_tags",
  s3_website_enabled: "s3_website_enabled",
  s3_no_object_lock: "s3_no_object_lock",
  s3_requester_pays: "s3_requester_pays",
  s3_acl_public: "s3_acl_public",
  s3_unencrypted_upload_allowed: "s3_unencrypted_upload_allowed",
  s3_no_replication: "s3_no_replication",
  s3_no_server_access_logging: "s3_no_server_access_logging",
  s3_no_cloudtrail_logging: "s3_no_cloudtrail_logging",
  s3_no_intelligent_tiering: "s3_no_intelligent_tiering",
  s3_object_lock_no_retention: "s3_object_lock_no_retention",
  s3_public_read_access: "s3_public_read_access",
  s3_public_write_access: "s3_public_write_access",
  s3_non_standard_encryption: "s3_non_standard_encryption",
  s3_bucket_key_disabled: "s3_bucket_key_disabled",
  s3_user_versioning_disabled: "s3_user_versioning_disabled",
  s3_unrestricted_policy: "s3_unrestricted_policy",
  s3_no_kms_encryption: "s3_no_kms_encryption",
  s3_no_access_point: "s3_no_access_point",

  // IAM
  over_permissive_iam: "over_permissive_iam",
  iam_user_no_mfa: "iam_user_no_mfa",
  iam_unused_access_key: "iam_unused_access_key",
  iam_inline_policy: "iam_inline_policy",
  iam_root_access_key: "iam_root_access_key",
  iam_user_with_console_access: "iam_user_with_console_access",
  iam_policy_wildcard: "iam_policy_wildcard",
  iam_root_mfa_disabled: "iam_root_mfa_disabled",
  iam_old_access_key: "iam_old_access_key",
  iam_no_password_policy: "iam_no_password_policy",
  iam_weak_password_policy: "iam_weak_password_policy",
  iam_user_direct_policy: "iam_user_direct_policy",
  iam_role_direct_policy: "iam_role_direct_policy",
  iam_empty_group: "iam_empty_group",
  iam_user_no_access_key: "iam_user_no_access_key",
  iam_no_saml_provider: "iam_no_saml_provider",
  iam_role_trusts_all: "iam_role_trusts_all",
  iam_role_admin_access: "iam_role_admin_access",
  iam_multiple_access_keys: "iam_multiple_access_keys",
  iam_no_credential_report: "iam_no_credential_report",
  iam_no_ssh_key: "iam_no_ssh_key",
  iam_user_no_tags: "iam_user_no_tags",
  iam_role_no_tags: "iam_role_no_tags",
  iam_policy_no_tags: "iam_policy_no_tags",
  iam_unused_policy: "iam_unused_policy",

  // EC2
  open_security_group_ingress: "open_security_group_ingress",
  open_security_group_egress: "open_security_group_egress",
  unused_security_group: "unused_security_group",
  ec2_instance_public_ip: "ec2_instance_public_ip",
  vpc_flow_logs_disabled: "vpc_flow_logs_disabled",
  sg_ssh_open: "sg_ssh_open",
  sg_rdp_open: "sg_rdp_open",
  default_vpc_in_use: "default_vpc_in_use",
  default_sg_in_use: "default_sg_in_use",
  detailed_monitoring_disabled: "detailed_monitoring_disabled",
  ebs_optimization_disabled: "ebs_optimization_disabled",
  termination_protection_disabled: "termination_protection_disabled",
  unattached_eip: "unattached_eip",
  instance_public_eni: "instance_public_eni",
  no_snapshots: "no_snapshots",
  unencrypted_snapshot: "unencrypted_snapshot",
  public_snapshot: "public_snapshot",
  public_ami: "public_ami",
  nacl_allow_all: "nacl_allow_all",
  route_table_open: "route_table_open",
  nat_gateway_no_eip: "nat_gateway_no_eip",
  vpn_not_encrypted: "vpn_not_encrypted",
  vpn_not_authenticated: "vpn_not_authenticated",
  ebs_delete_on_termination_disabled: "ebs_delete_on_termination_disabled",
  instance_no_iam_profile: "instance_no_iam_profile",
  source_dest_check_enabled: "source_dest_check_enabled",
  key_pair_no_tags: "key_pair_no_tags",
  sg_no_description: "sg_no_description",
  instance_default_tenancy: "instance_default_tenancy",
  instance_shutdown_behavior: "instance_shutdown_behavior",

  // CloudTrail
  cloudtrail_not_logging: "cloudtrail_not_logging",
  cloudtrail_not_multi_region: "cloudtrail_not_multi_region",
  cloudtrail_no_log_file_validation: "cloudtrail_no_log_file_validation",
  cloudtrail_bucket_public: "cloudtrail_bucket_public",
  cloudtrail_bucket_encryption_disabled:
    "cloudtrail_bucket_encryption_disabled",
  cloudtrail_no_kms: "cloudtrail_no_kms",
  cloudtrail_not_recording: "cloudtrail_not_recording",
  cloudtrail_no_org_trail: "cloudtrail_no_org_trail",
  cloudtrail_no_event_selectors: "cloudtrail_no_event_selectors",
  cloudtrail_mgmt_events_disabled: "cloudtrail_mgmt_events_disabled",
  cloudtrail_no_data_events: "cloudtrail_no_data_events",
  cloudtrail_no_cloudwatch: "cloudtrail_no_cloudwatch",
  cloudtrail_bucket_versioning_disabled:
    "cloudtrail_bucket_versioning_disabled",
  cloudtrail_bucket_no_mfa_delete: "cloudtrail_bucket_no_mfa_delete",
  cloudtrail_bucket_no_logging: "cloudtrail_bucket_no_logging",
  cloudtrail_shadow_trails: "cloudtrail_shadow_trails",
  cloudtrail_no_sns: "cloudtrail_no_sns",
  cloudtrail_bucket_public_policy: "cloudtrail_bucket_public_policy",
  cloudtrail_no_log_digest: "cloudtrail_no_log_digest",
  cloudtrail_no_tags: "cloudtrail_no_tags",
  cloudtrail_too_many_trails: "cloudtrail_too_many_trails",
  cloudtrail_no_read_events: "cloudtrail_no_read_events",
  cloudtrail_bucket_no_lifecycle: "cloudtrail_bucket_no_lifecycle",
  cloudtrail_no_advanced_selectors: "cloudtrail_no_advanced_selectors",
  cloudtrail_invalid_name: "cloudtrail_invalid_name",

  // GuardDuty
  guardduty_disabled: "guardduty_disabled",
  guardduty_finding_freq_not_optimal: "guardduty_finding_freq_not_optimal",
  guardduty_no_s3_protection: "guardduty_no_s3_protection",
  guardduty_no_eks_protection: "guardduty_no_eks_protection",
  guardduty_no_lambda_protection: "guardduty_no_lambda_protection",
  guardduty_no_rds_protection: "guardduty_no_rds_protection",
  guardduty_no_cloudwatch_logs: "guardduty_no_cloudwatch_logs",
  guardduty_no_threat_intel: "guardduty_no_threat_intel",
  guardduty_findings_not_archived: "guardduty_findings_not_archived",
  guardduty_no_ip_set: "guardduty_no_ip_set",
  guardduty_no_member_accounts: "guardduty_no_member_accounts",
  guardduty_high_severity_findings: "guardduty_high_severity_findings",
  guardduty_detector_no_tags: "guardduty_detector_no_tags",
  guardduty_no_member_invitations: "guardduty_no_member_invitations",
  guardduty_no_master_account: "guardduty_no_master_account",
  guardduty_no_vpc_flow_logs: "guardduty_no_vpc_flow_logs",
  guardduty_no_cloudtrail: "guardduty_no_cloudtrail",
  guardduty_no_findings_export: "guardduty_no_findings_export",
  guardduty_no_sns_notification: "guardduty_no_sns_notification",
  guardduty_orphaned_detector: "guardduty_orphaned_detector",
  guardduty_no_custom_ip_set: "guardduty_no_custom_ip_set",
  guardduty_no_custom_threat_intel: "guardduty_no_custom_threat_intel",
  guardduty_malware_protection_disabled:
    "guardduty_malware_protection_disabled",
  guardduty_runtime_monitoring_disabled:
    "guardduty_runtime_monitoring_disabled",

  // EBS
  ebs_volume_unencrypted: "ebs_volume_unencrypted",
  ebs_no_snapshots: "ebs_no_snapshots",
  ebs_snapshot_public: "ebs_snapshot_public",
  ebs_snapshot_unencrypted: "ebs_snapshot_unencrypted",
  ebs_no_tags: "ebs_no_tags",
  ebs_default_kms_key: "ebs_default_kms_key",
  ebs_snapshot_shared: "ebs_snapshot_shared",
  ebs_no_delete_on_termination: "ebs_no_delete_on_termination",
  ebs_unattached: "ebs_unattached",
  ebs_old_snapshots: "ebs_old_snapshots",
  ebs_snapshot_no_description: "ebs_snapshot_no_description",
  ebs_no_description: "ebs_no_description",
  ebs_io_unencrypted: "ebs_io_unencrypted",
  ebs_gp2_large: "ebs_gp2_large",
  ebs_snapshot_copy_encrypted: "ebs_snapshot_copy_encrypted",
  ebs_iops_not_optimized: "ebs_iops_not_optimized",
  ebs_snapshots_too_many: "ebs_snapshots_too_many",
  ebs_volume_excessive: "ebs_volume_excessive",
  ebs_copy_no_encryption: "ebs_copy_no_encryption",
  ebs_no_backup_plan: "ebs_no_backup_plan",
  ebs_snapshot_copy_unencrypted: "ebs_snapshot_copy_unencrypted",
  ebs_no_fast_restore: "ebs_no_fast_restore",
  ebs_old_volume_type: "ebs_old_volume_type",

  // RDS
  rds_instance_unencrypted: "rds_instance_unencrypted",
  rds_instance_public_access: "rds_instance_public_access",
  rds_no_backup: "rds_no_backup",
  rds_low_backup_retention: "rds_low_backup_retention",
  rds_no_multi_az: "rds_no_multi_az",
  rds_no_enhanced_monitoring: "rds_no_enhanced_monitoring",
  rds_no_deletion_protection: "rds_no_deletion_protection",
  rds_no_copy_snapshots: "rds_no_copy_snapshots",
  rds_auto_minor_upgrade: "rds_auto_minor_upgrade",
  rds_no_performance_insights: "rds_no_performance_insights",
  rds_iam_auth_disabled: "rds_iam_auth_disabled",
  rds_default_port: "rds_default_port",
  rds_default_param_group: "rds_default_param_group",
  rds_cluster_unencrypted: "rds_cluster_unencrypted",
  rds_cluster_public: "rds_cluster_public",
  rds_no_automated_backup: "rds_no_automated_backup",
  rds_snapshot_public: "rds_snapshot_public",
  rds_no_tags: "rds_no_tags",
  rds_storage_not_encrypted: "rds_storage_not_encrypted",
  rds_no_option_group: "rds_no_option_group",
  rds_no_vpc: "rds_no_vpc",
  rds_no_cloudtrail: "rds_no_cloudtrail",
  rds_cluster_low_retention: "rds_cluster_low_retention",
  rds_default_sg: "rds_default_sg",
  rds_no_kms_key: "rds_no_kms_key",
  rds_unsupported_engine: "rds_unsupported_engine",
  rds_no_audit_logs: "rds_no_audit_logs",

  // Lambda
  lambda_overpermissive_role: "lambda_overpermissive_role",
  lambda_public_access: "lambda_public_access",
  lambda_no_vpc: "lambda_no_vpc",
  lambda_no_dlq: "lambda_no_dlq",
  lambda_xray_disabled: "lambda_xray_disabled",
  lambda_high_timeout: "lambda_high_timeout",
  lambda_high_memory: "lambda_high_memory",
  lambda_no_encryption: "lambda_no_encryption",
  lambda_no_logging: "lambda_no_logging",
  lambda_outdated_runtime: "lambda_outdated_runtime",
  lambda_no_reserved_concurrency: "lambda_no_reserved_concurrency",
  lambda_no_code_signing: "lambda_no_code_signing",
  lambda_env_not_encrypted: "lambda_env_not_encrypted",
  lambda_no_tags: "lambda_no_tags",
  lambda_no_description: "lambda_no_description",
  lambda_unrestricted_vpc: "lambda_unrestricted_vpc",
  lambda_ephemeral_unencrypted: "lambda_ephemeral_unencrypted",
  lambda_layer_not_vetted: "lambda_layer_not_vetted",
  lambda_function_url_enabled: "lambda_function_url_enabled",
  lambda_function_url_no_auth: "lambda_function_url_no_auth",
  lambda_function_url_cors_all: "lambda_function_url_cors_all",
  lambda_image_scan_disabled: "lambda_image_scan_disabled",
  lambda_role_trusts_all: "lambda_role_trusts_all",
  lambda_no_resource_policy: "lambda_no_resource_policy",

  // SSM
  ssm_parameter_unencrypted: "ssm_parameter_unencrypted",
  ssm_param_public_tier: "ssm_param_public_tier",
  ssm_document_public: "ssm_document_public",
  ssm_no_session_logging: "ssm_no_session_logging",
  ssm_param_no_tags: "ssm_param_no_tags",
  ssm_doc_no_description: "ssm_doc_no_description",
  ssm_patch_manager_disabled: "ssm_patch_manager_disabled",
  ssm_maintenance_window_no_logging: "ssm_maintenance_window_no_logging",
  ssm_no_host_mgmt_role: "ssm_no_host_mgmt_role",
  ssm_no_ops_center: "ssm_no_ops_center",
  ssm_automation_no_logging: "ssm_automation_no_logging",
  ssm_command_no_logging: "ssm_command_no_logging",
  ssm_doc_no_versioning: "ssm_doc_no_versioning",
  ssm_param_permissive: "ssm_param_permissive",
  ssm_param_stale: "ssm_param_stale",
  ssm_doc_stale: "ssm_doc_stale",
  ssm_no_inventory: "ssm_no_inventory",
  ssm_compliance_disabled: "ssm_compliance_disabled",
  ssm_state_manager_disabled: "ssm_state_manager_disabled",
  ssm_param_limit_high: "ssm_param_limit_high",
  ssm_default_kms_key: "ssm_default_kms_key",
  ssm_doc_hardcoded_creds: "ssm_doc_hardcoded_creds",
  ssm_param_no_policy: "ssm_param_no_policy",
  ssm_automation_no_role: "ssm_automation_no_role",
  ssm_no_change_calendar: "ssm_no_change_calendar",

  // API Gateway
  apigateway_open_resource: "apigateway_open_resource",
  apigateway_no_logging: "apigateway_no_logging",
  apigateway_no_waf: "apigateway_no_waf",
  apigateway_no_throttling: "apigateway_no_throttling",
  apigateway_no_cache: "apigateway_no_cache",
  apigateway_no_xray: "apigateway_no_xray",
  apigateway_no_ssl: "apigateway_no_ssl",
  apigateway_no_api_endpoint: "apigateway_no_api_endpoint",
  apigateway_method_no_auth: "apigateway_method_no_auth",
  apigateway_no_access_logs: "apigateway_no_access_logs",
  apigateway_no_auth: "apigateway_no_auth",
  apigateway_no_request_validation: "apigateway_no_request_validation",
  apigateway_no_domain_cert: "apigateway_no_domain_cert",
  apigateway_certificate_expired: "apigateway_certificate_expired",
  apigateway_no_execution_logs: "apigateway_no_execution_logs",
  apigateway_cors_all_origins: "apigateway_cors_all_origins",
  apigateway_binary_media_unencrypted: "apigateway_binary_media_unencrypted",
  apigateway_no_api_key: "apigateway_no_api_key",
  apigateway_plaintext_logs: "apigateway_plaintext_logs",
};

export const RESOURCES_MAP: Record<string, string[]> = {
  s3: [
    Vulnerability.public_s3_bucket,
    Vulnerability.s3_bucket_versioning_disabled,
    Vulnerability.s3_bucket_logging_disabled,
    Vulnerability.s3_bucket_block_public_access_disabled,
    Vulnerability.unencrypted_s3_bucket,
    Vulnerability.s3_mfa_delete_disabled,
    Vulnerability.s3_no_lifecycle,
    Vulnerability.s3_cors_all_origins,
    Vulnerability.s3_bucket_no_tags,
    Vulnerability.s3_website_enabled,
    Vulnerability.s3_no_object_lock,
    Vulnerability.s3_requester_pays,
    Vulnerability.s3_acl_public,
    Vulnerability.s3_unencrypted_upload_allowed,
    Vulnerability.s3_no_replication,
    Vulnerability.s3_no_server_access_logging,
    Vulnerability.s3_no_cloudtrail_logging,
    Vulnerability.s3_no_intelligent_tiering,
    Vulnerability.s3_object_lock_no_retention,
    Vulnerability.s3_public_read_access,
    Vulnerability.s3_public_write_access,
    Vulnerability.s3_non_standard_encryption,
    Vulnerability.s3_bucket_key_disabled,
    Vulnerability.s3_user_versioning_disabled,
    Vulnerability.s3_unrestricted_policy,
    Vulnerability.s3_no_kms_encryption,
    Vulnerability.s3_no_access_point,
  ],
  iam: [
    Vulnerability.over_permissive_iam,
    Vulnerability.iam_user_no_mfa,
    Vulnerability.iam_unused_access_key,
    Vulnerability.iam_inline_policy,
    Vulnerability.iam_root_access_key,
    Vulnerability.iam_user_with_console_access,
    Vulnerability.iam_policy_wildcard,
    Vulnerability.iam_root_mfa_disabled,
    Vulnerability.iam_old_access_key,
    Vulnerability.iam_no_password_policy,
    Vulnerability.iam_weak_password_policy,
    Vulnerability.iam_user_direct_policy,
    Vulnerability.iam_role_direct_policy,
    Vulnerability.iam_empty_group,
    Vulnerability.iam_user_no_access_key,
    Vulnerability.iam_no_saml_provider,
    Vulnerability.iam_role_trusts_all,
    Vulnerability.iam_role_admin_access,
    Vulnerability.iam_multiple_access_keys,
    Vulnerability.iam_no_credential_report,
    Vulnerability.iam_no_ssh_key,
    Vulnerability.iam_user_no_tags,
    Vulnerability.iam_role_no_tags,
    Vulnerability.iam_policy_no_tags,
    Vulnerability.iam_unused_policy,
  ],
  ec2: [
    Vulnerability.open_security_group_ingress,
    Vulnerability.open_security_group_egress,
    Vulnerability.unused_security_group,
    Vulnerability.ec2_instance_public_ip,
    Vulnerability.vpc_flow_logs_disabled,
    Vulnerability.sg_ssh_open,
    Vulnerability.sg_rdp_open,
    Vulnerability.default_vpc_in_use,
    Vulnerability.default_sg_in_use,
    Vulnerability.detailed_monitoring_disabled,
    Vulnerability.ebs_optimization_disabled,
    Vulnerability.termination_protection_disabled,
    Vulnerability.unattached_eip,
    Vulnerability.instance_public_eni,
    Vulnerability.no_snapshots,
    Vulnerability.unencrypted_snapshot,
    Vulnerability.public_snapshot,
    Vulnerability.public_ami,
    Vulnerability.nacl_allow_all,
    Vulnerability.route_table_open,
    Vulnerability.nat_gateway_no_eip,
    Vulnerability.vpn_not_encrypted,
    Vulnerability.vpn_not_authenticated,
    Vulnerability.ebs_delete_on_termination_disabled,
    Vulnerability.instance_no_iam_profile,
    Vulnerability.source_dest_check_enabled,
    Vulnerability.key_pair_no_tags,
    Vulnerability.sg_no_description,
    Vulnerability.instance_default_tenancy,
    Vulnerability.instance_shutdown_behavior,
  ],
  cloudtrail: [
    Vulnerability.cloudtrail_not_logging,
    Vulnerability.cloudtrail_not_multi_region,
    Vulnerability.cloudtrail_no_log_file_validation,
    Vulnerability.cloudtrail_bucket_public,
    Vulnerability.cloudtrail_bucket_encryption_disabled,
    Vulnerability.cloudtrail_no_kms,
    Vulnerability.cloudtrail_not_recording,
    Vulnerability.cloudtrail_no_org_trail,
    Vulnerability.cloudtrail_no_event_selectors,
    Vulnerability.cloudtrail_mgmt_events_disabled,
    Vulnerability.cloudtrail_no_data_events,
    Vulnerability.cloudtrail_no_cloudwatch,
    Vulnerability.cloudtrail_bucket_versioning_disabled,
    Vulnerability.cloudtrail_bucket_no_mfa_delete,
    Vulnerability.cloudtrail_bucket_no_logging,
    Vulnerability.cloudtrail_shadow_trails,
    Vulnerability.cloudtrail_no_sns,
    Vulnerability.cloudtrail_bucket_public_policy,
    Vulnerability.cloudtrail_no_log_digest,
    Vulnerability.cloudtrail_no_tags,
    Vulnerability.cloudtrail_too_many_trails,
    Vulnerability.cloudtrail_no_read_events,
    Vulnerability.cloudtrail_bucket_no_lifecycle,
    Vulnerability.cloudtrail_no_advanced_selectors,
    Vulnerability.cloudtrail_invalid_name,
  ],
  guardduty: [
    Vulnerability.guardduty_disabled,
    Vulnerability.guardduty_finding_freq_not_optimal,
    Vulnerability.guardduty_no_s3_protection,
    Vulnerability.guardduty_no_eks_protection,
    Vulnerability.guardduty_no_lambda_protection,
    Vulnerability.guardduty_no_rds_protection,
    Vulnerability.guardduty_no_cloudwatch_logs,
    Vulnerability.guardduty_no_threat_intel,
    Vulnerability.guardduty_findings_not_archived,
    Vulnerability.guardduty_no_ip_set,
    Vulnerability.guardduty_no_member_accounts,
    Vulnerability.guardduty_high_severity_findings,
    Vulnerability.guardduty_detector_no_tags,
    Vulnerability.guardduty_no_member_invitations,
    Vulnerability.guardduty_no_master_account,
    Vulnerability.guardduty_no_vpc_flow_logs,
    Vulnerability.guardduty_no_cloudtrail,
    Vulnerability.guardduty_no_findings_export,
    Vulnerability.guardduty_no_sns_notification,
    Vulnerability.guardduty_orphaned_detector,
    Vulnerability.guardduty_no_custom_ip_set,
    Vulnerability.guardduty_no_custom_threat_intel,
    Vulnerability.guardduty_malware_protection_disabled,
    Vulnerability.guardduty_runtime_monitoring_disabled,
  ],
  ebs: [
    Vulnerability.ebs_volume_unencrypted,
    Vulnerability.ebs_no_snapshots,
    Vulnerability.ebs_snapshot_public,
    Vulnerability.ebs_snapshot_unencrypted,
    Vulnerability.ebs_no_tags,
    Vulnerability.ebs_default_kms_key,
    Vulnerability.ebs_snapshot_shared,
    Vulnerability.ebs_no_delete_on_termination,
    Vulnerability.ebs_unattached,
    Vulnerability.ebs_old_snapshots,
    Vulnerability.ebs_snapshot_no_description,
    Vulnerability.ebs_no_description,
    Vulnerability.ebs_io_unencrypted,
    Vulnerability.ebs_gp2_large,
    Vulnerability.ebs_snapshot_copy_encrypted,
    Vulnerability.ebs_iops_not_optimized,
    Vulnerability.ebs_snapshots_too_many,
    Vulnerability.ebs_volume_excessive,
    Vulnerability.ebs_copy_no_encryption,
    Vulnerability.ebs_no_backup_plan,
    Vulnerability.ebs_snapshot_copy_unencrypted,
    Vulnerability.ebs_no_fast_restore,
    Vulnerability.ebs_old_volume_type,
  ],
  rds: [
    Vulnerability.rds_instance_unencrypted,
    Vulnerability.rds_instance_public_access,
    Vulnerability.rds_no_backup,
    Vulnerability.rds_low_backup_retention,
    Vulnerability.rds_no_multi_az,
    Vulnerability.rds_no_enhanced_monitoring,
    Vulnerability.rds_no_deletion_protection,
    Vulnerability.rds_no_copy_snapshots,
    Vulnerability.rds_auto_minor_upgrade,
    Vulnerability.rds_no_performance_insights,
    Vulnerability.rds_iam_auth_disabled,
    Vulnerability.rds_default_port,
    Vulnerability.rds_default_param_group,
    Vulnerability.rds_cluster_unencrypted,
    Vulnerability.rds_cluster_public,
    Vulnerability.rds_no_automated_backup,
    Vulnerability.rds_snapshot_public,
    Vulnerability.rds_no_tags,
    Vulnerability.rds_storage_not_encrypted,
    Vulnerability.rds_no_option_group,
    Vulnerability.rds_no_vpc,
    Vulnerability.rds_no_cloudtrail,
    Vulnerability.rds_cluster_low_retention,
    Vulnerability.rds_default_sg,
    Vulnerability.rds_no_kms_key,
    Vulnerability.rds_unsupported_engine,
    Vulnerability.rds_no_audit_logs,
  ],
  ssm: [
    Vulnerability.ssm_parameter_unencrypted,
    Vulnerability.ssm_param_public_tier,
    Vulnerability.ssm_document_public,
    Vulnerability.ssm_no_session_logging,
    Vulnerability.ssm_param_no_tags,
    Vulnerability.ssm_doc_no_description,
    Vulnerability.ssm_patch_manager_disabled,
    Vulnerability.ssm_maintenance_window_no_logging,
    Vulnerability.ssm_no_host_mgmt_role,
    Vulnerability.ssm_no_ops_center,
    Vulnerability.ssm_automation_no_logging,
    Vulnerability.ssm_command_no_logging,
    Vulnerability.ssm_doc_no_versioning,
    Vulnerability.ssm_param_permissive,
    Vulnerability.ssm_param_stale,
    Vulnerability.ssm_doc_stale,
    Vulnerability.ssm_no_inventory,
    Vulnerability.ssm_compliance_disabled,
    Vulnerability.ssm_state_manager_disabled,
    Vulnerability.ssm_param_limit_high,
    Vulnerability.ssm_default_kms_key,
    Vulnerability.ssm_doc_hardcoded_creds,
    Vulnerability.ssm_param_no_policy,
    Vulnerability.ssm_automation_no_role,
    Vulnerability.ssm_no_change_calendar,
  ],
  lambda: [
    Vulnerability.lambda_overpermissive_role,
    Vulnerability.lambda_public_access,
    Vulnerability.lambda_no_vpc,
    Vulnerability.lambda_no_dlq,
    Vulnerability.lambda_xray_disabled,
    Vulnerability.lambda_high_timeout,
    Vulnerability.lambda_high_memory,
    Vulnerability.lambda_no_encryption,
    Vulnerability.lambda_no_logging,
    Vulnerability.lambda_outdated_runtime,
    Vulnerability.lambda_no_reserved_concurrency,
    Vulnerability.lambda_no_code_signing,
    Vulnerability.lambda_env_not_encrypted,
    Vulnerability.lambda_no_tags,
    Vulnerability.lambda_no_description,
    Vulnerability.lambda_unrestricted_vpc,
    Vulnerability.lambda_ephemeral_unencrypted,
    Vulnerability.lambda_layer_not_vetted,
    Vulnerability.lambda_function_url_enabled,
    Vulnerability.lambda_function_url_no_auth,
    Vulnerability.lambda_function_url_cors_all,
    Vulnerability.lambda_image_scan_disabled,
    Vulnerability.lambda_role_trusts_all,
    Vulnerability.lambda_no_resource_policy,
  ],
  apigateway: [
    Vulnerability.apigateway_open_resource,
    Vulnerability.apigateway_no_logging,
    Vulnerability.apigateway_no_waf,
    Vulnerability.apigateway_no_throttling,
    Vulnerability.apigateway_no_cache,
    Vulnerability.apigateway_no_xray,
    Vulnerability.apigateway_no_ssl,
    Vulnerability.apigateway_no_api_endpoint,
    Vulnerability.apigateway_method_no_auth,
    Vulnerability.apigateway_no_access_logs,
    Vulnerability.apigateway_no_auth,
    Vulnerability.apigateway_no_request_validation,
    Vulnerability.apigateway_no_domain_cert,
    Vulnerability.apigateway_certificate_expired,
    Vulnerability.apigateway_no_execution_logs,
    Vulnerability.apigateway_cors_all_origins,
    Vulnerability.apigateway_binary_media_unencrypted,
    Vulnerability.apigateway_no_api_key,
    Vulnerability.apigateway_plaintext_logs,
  ],
};
