const Vulnerability = {
  public_s3_bucket: "public_s3_bucket",
  s3_bucket_versioning_disabled: "s3_bucket_versioning_disabled",
  s3_bucket_logging_disabled: "s3_bucket_logging_disabled",
  s3_bucket_block_public_access_disabled:
    "s3_bucket_block_public_access_disabled",
  unencrypted_s3_bucket: "unencrypted_s3_bucket",
  vpc_flow_logs_disabled: "vpc_flow_logs_disabled",
  over_permissive_iam: "over_permissive_iam",
  iam_user_no_mfa: "iam_user_no_mfa",
  iam_unused_access_key: "iam_unused_access_key",
  iam_inline_policy: "iam_inline_policy",
  iam_root_access_key: "iam_root_access_key",
  iam_user_with_console_access: "iam_user_with_console_access",
  open_security_group_ingress: "open_security_group_ingress",
  open_security_group_egress: "open_security_group_egress",
  unused_security_group: "unused_security_group",
  ec2_instance_public_ip: "ec2_instance_public_ip",
  cloudtrail_not_logging: "cloudtrail_not_logging",
  cloudtrail_not_multi_region: "cloudtrail_not_multi_region",
  cloudtrail_no_log_file_validation: "cloudtrail_no_log_file_validation",
  cloudtrail_bucket_public: "cloudtrail_bucket_public",
  cloudtrail_bucket_encryption_disabled:
    "cloudtrail_bucket_encryption_disabled",
  guardduty_disabled: "guardduty_disabled",
  ebs_volume_unencrypted: "ebs_volume_unencrypted",
  rds_instance_unencrypted: "rds_instance_unencrypted",
  rds_instance_public_access: "rds_instance_public_access",
  ssm_parameter_unencrypted: "ssm_parameter_unencrypted",
  lambda_overpermissive_role: "lambda_overpermissive_role",
  lambda_public_access: "lambda_public_access",
  apigateway_open_resource: "apigateway_open_resource",
};

export const RESOURCES_MAP: Record<string, string[]> = {
  s3: [
    Vulnerability.public_s3_bucket,
    Vulnerability.s3_bucket_versioning_disabled,
    Vulnerability.s3_bucket_logging_disabled,
    Vulnerability.s3_bucket_block_public_access_disabled,
    Vulnerability.unencrypted_s3_bucket,
    Vulnerability.vpc_flow_logs_disabled,
  ],
  iam: [
    Vulnerability.over_permissive_iam,
    Vulnerability.iam_user_no_mfa,
    Vulnerability.iam_unused_access_key,
    Vulnerability.iam_inline_policy,
    Vulnerability.iam_root_access_key,
    Vulnerability.iam_user_with_console_access,
  ],
  ec2: [
    Vulnerability.open_security_group_ingress,
    Vulnerability.open_security_group_egress,
    Vulnerability.unused_security_group,
    Vulnerability.ec2_instance_public_ip,
  ],
  cloudtrail: [
    Vulnerability.cloudtrail_not_logging,
    Vulnerability.cloudtrail_not_multi_region,
    Vulnerability.cloudtrail_no_log_file_validation,
    Vulnerability.cloudtrail_bucket_public,
    Vulnerability.cloudtrail_bucket_encryption_disabled,
  ],
  guardduty: [Vulnerability.guardduty_disabled],
  ebs: [Vulnerability.ebs_volume_unencrypted],
  rds: [
    Vulnerability.rds_instance_unencrypted,
    Vulnerability.rds_instance_public_access,
  ],
  ssm: [Vulnerability.ssm_parameter_unencrypted],
  lambda: [
    Vulnerability.lambda_overpermissive_role,
    Vulnerability.lambda_public_access,
  ],
  apigateway: [Vulnerability.apigateway_open_resource],
};
